world_width = 30.0
world_height = 20.0
gravity = [0.0, 0.0]
timestep = 0.016666667
restitution = 0.95
position_correction = 0.8
num_steps = 150  # Enough to see the collision and break
record_trajectory = true
seed = 0

# Cue ball
[[circles]]
position = [5.0, 10.0]
velocity = [15.0, 0.1]
radius = 0.5
mass = 1.2

# Apex ball
[[circles]]
position = [20.0, 10.0]
velocity = [0.0, 0.0]
radius = 0.5
mass = 1.0

# Row 2, ball 1
[[circles]]
position = [20.866, 9.5]
velocity = [0.0, 0.0]
radius = 0.5
mass = 1.0

# Row 2, ball 2
[[circles]]
position = [20.866, 10.5]
velocity = [0.0, 0.0]
radius = 0.5
mass = 1.0