world_width = 100.0
world_height = 100.0
gravity = [0.0, -9.81]
timestep = 0.016666667
restitution = 0.8
position_correction = 0.8
num_steps = 120
record_trajectory = true
seed = 0

[[circles]]
position = [50.0, 80.0]
velocity = [0.0, 0.0]
radius = 5.0
mass = 1.0