[package]
name = "physics_guest"
version = "0.1.0"
edition = "2021"

[dependencies]
risc0-zkvm = { version = "^2.3.1", default-features = false }
serde = { version = "1.0", default-features = false, features = ["derive"] }
determinisk-core = { version = "0.1.0", default-features = false }
